spring:
  application:
    name: Comics
  jpa:
    hibernate:
      ddl-auto: update
      use-new-id-generator-mappings: false
  datasource:
#    url: jdbc:mysql://localhost:3306/comicsdb
    url: jdbc:h2:mem:test
    username: root
    password:
  h2:
    console:
      enabled: true